### ISSUE TITLE
Error when pasting an image from the clipboard (Anki 23.10)

### ISSUE THREAD

**Issue by cjdduarte** [BlueGreenMagick/Edit-Field-During-Review-Cloze#109]
Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-24 13:11:19
Extensões possivelmente envolvidas: ⁨Edit Field During Review Cloze⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 660, in _onBridgeCmd
  File "_aqt.hooks", line 5376, in __call__
  File "D:\Anki\Anki.2.1.data\addons21\385888438\reviewer.py", line 175, in handle_pycmd_message
    mime = mw.app.clipboard().mimeData(mode=QClipboard.Clipboard)
AttributeError: type object 'QClipboard' has no attribute 'Clipboard'

**Comment by cjdduarte** [comment]
This code work:

` elif message == "EFDRC!paste":
        # From aqt.editor.Editor._onPaste, doPaste.
        mime = mw.app.clipboard().mimeData(mode=QClipboard.Mode.Clipboard)
       `

**Comment by BlueGreenMagick** [comment]
Thanks for the bug report and the fix!
