### ISSUE TITLE
conflict with "hjp-linkmaster: 🧷 思维导图. mind graph, roaming reviewer, bilinker" ,it can't save when edit in review

### ISSUE THREAD

**Issue by Nirvana-Zero** [BlueGreenMagick/Edit-Field-During-Review-Cloze#125]
**Describe the bug**
I'm experiencing a conflict with the "hjp-linkmaster: 🧷 思维导图. mind graph, roaming reviewer, bilinker"add-ons. It prevents me from saving changes while editing during review. I'm unsure how to resolve this issue. Can you help?

**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button. Please paste the contents below.
Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 689, in _onBridgeCmd
  File "_aqt.hooks", line 5416, in __call__
  File "C:\Users\ddd\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 138, in handle_pycmd_message
    saveField(note, fld, new_val)
  File "C:\Users\ddd\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 81, in saveField
    txt = Editor.mungeHTML(editorwv.editor, val)
  File "aqt.editor", line 520, in mungeHTML
  File "_aqt.hooks", line 2760, in __call__
  File "C:\Users\ddd\AppData\Roaming\Anki2\addons21\1420819673\lib\bilink\in_text_admin\backlink_monitor.py", line 52, in handle_editor_will_munge_html
    if editor.currentField is None:
AttributeError: 'semiEditor' object has no attribute 'currentField'

**Comment by BlueGreenMagick** [comment]
Should be fixed!
