### ISSUE TITLE
Encounter Error With Latest Version of Anki

### ISSUE THREAD

**Issue by elony314** [BlueGreenMagick/Edit-Field-During-Review-Cloze#34]
I have disable all other plugins. 
The error popups when I edit a field and loose focus of that field.
```
Debug info:
Anki 2.1.32 (dee7d45d) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-27 19:05:39
Add-ons possibly involved: ⁨Edit Field During Review Cloze⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-10>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File ~/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "~/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "~/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt/editor.py", line 421, in mungeHTML
  File "aqt/gui_hooks.py", line 1606, in __call__
  File "aqt/editor.py", line 1219, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'
```

**Comment by AndreGDFeliciano** [comment]
I get the same error,
Temporary workaround: in my computer that only appears the first time we use the add-on (on each anki restart) so if you want to use it:

1. Use the add-on as usual
2. lose focus of the field (you don't actually have to write anything)
3. Close error
4. try again

**Comment by itsdomme** [comment]
I have the same issue with 2.1.30 and even with the original addon.

**Comment by hugomarins** [comment]
Same issue for me:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-11 18:15:35

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-62>", line 2, in _linkHandler
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt\editor.py", line 421, in mungeHTML
  File "aqt\gui_hooks.py", line 1606, in __call__
  File "aqt\editor.py", line 1217, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'
