### ISSUE TITLE
error windows are always displaying every the first edit!

### ISSUE THREAD

**Issue by loveAnkisomuch** [BlueGreenMagick/Edit-Field-During-Review-Cloze#39]
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-17 00:30:26

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-42>", line 2, in linkHandler_wrapper
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt\editor.py", line 423, in mungeHTML
  File "aqt\gui_hooks.py", line 1606, in __call__
  File "aqt\editor.py", line 1225, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'

**Comment by anthelli** [comment]
Hi, I think I got a similar problem, although, after the first error message, I have no problem using the add-on. 
 
`Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-26 15:32:02

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-32>", line 2, in _linkHandler
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\mxjvi\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "C:\Users\mxjvi\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "C:\Users\mxjvi\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt\editor.py", line 423, in mungeHTML
  File "aqt\gui_hooks.py", line 1606, in __call__
  File "aqt\editor.py", line 1225, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'`

**Comment by spartandrew18** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.37 (6d596c8f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-13 13:25:22

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "<decorator-gen-40>", line 2, in _linkHandler
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\879473266\open_in_external.py", line 166, in myLinkHandler
    return _old(self, url)
  File "<decorator-gen-24>", line 2, in _linkHandler
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt\editor.py", line 447, in mungeHTML
  File "aqt\hooks_gen.py", line 1624, in __call__
  File "aqt\editor.py", line 1249, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'

**Comment by BlueGreenMagick** [comment]
This has been fixed in the latest version with #37. Sorry for the long wait!
