### ISSUE TITLE
Incompatibility with Anki 2.1.20 (beta 5)

### ISSUE THREAD

**Issue by marreromarco** [BlueGreenMagick/Edit-Field-During-Review-Cloze#4]
Recent changes in Anki 2.1.20 made the add-on incompatible. 

It is still possible to review cards and Anki doesn't crash but the add-on doesn't work:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (d428b3b4) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 30, in cmd
  File "aqt\webview.py", line 96, in _onCmd
  File "aqt\webview.py", line 423, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-50>", line 2, in _linkHandler
  File "lib\site-packages\anki\hooks.py", line 506, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 503, in repl
  File "C:\Users\marre\AppData\Roaming\Anki2\addons21\385888438\__init__.py", line 89, in myLinkHandler
    reviewer.card._getQA(reload=True)
AttributeError: 'Card' object has no attribute '_getQA'

**Comment by BlueGreenMagick** [comment]
Thanks for taking time to posting this issue! This was fixed in the latest update v3.1.
